/**
 * Event Template Service
 * Manages recurring event templates and draft generation pipeline.
 */

import { prisma } from "../controllers/databaseController.js";
import { createEvent, logEventAudit, upsertEventAnnouncements } from "./eventService.js";
import { EVENT_VISIBILITY, normaliseRankSlugs } from "../lib/eventAccess.js";

/** Reject anything outside the known set so a bad payload cannot invent a visibility. */
function coerceVisibility(value, fallback = "public") {
  const v = String(value ?? "").trim().toLowerCase();
  return EVENT_VISIBILITY.includes(v) ? v : fallback;
}

/**
 * Get all active templates.
 */
export async function getTemplates({ includeDeleted = false } = {}) {
  const where = {};
  if (!includeDeleted) where.deletedAt = null;

  return prisma.event_templates.findMany({
    where,
    include: { defaultHosts: true, rankAccess: true, _count: { select: { events: true } } },
    orderBy: { createdAt: "asc" },
  });
}

/**
 * Get a single template by ID.
 */
export async function getTemplateById(templateId, includeDeleted = false) {
  const tmpl = await prisma.event_templates.findUnique({
    where: { templateId: parseInt(templateId) },
    include: {
      defaultHosts: true,
      rankAccess: true,
      announcements: { orderBy: { id: "asc" } },
      events: {
        where: { deletedAt: null },
        orderBy: { startAt: "desc" },
        take: 10,
        select: { eventId: true, title: true, startAt: true, status: true },
      },
    },
  });

  if (!tmpl) return null;
  if (!includeDeleted && tmpl.deletedAt) return null;

  return tmpl;
}

/**
 * Create a new event template.
 */
export async function createTemplate(data, creatorId) {
  const recurrenceType = data.recurrenceType || "weekly";
  const isOnce = recurrenceType === "once";

  const tmpl = await prisma.event_templates.create({
    data: {
      title: data.title,
      description: data.description || null,
      teaserDescription: data.teaserDescription || null,
      defaultStartTime: data.defaultStartTime || null,
      defaultEndTime: data.defaultEndTime || null,
      defaultDurationMins: data.defaultDurationMins || null,
      timezone: data.timezone || "UTC",
      recurrenceType,
      recurrenceDays: data.recurrenceDays || undefined,
      recurrenceEveryDays: data.recurrenceEveryDays || null,
      draftAdvanceDays: data.draftAdvanceDays || 7,
      autoGenerateDrafts: isOnce ? false : (data.autoGenerateDrafts !== undefined ? data.autoGenerateDrafts : true),
      locationLabel: data.locationLabel || null,
      locationType: data.locationType || null,
      locationDiscordChannelId: data.locationDiscordChannelId || null,
      serverName: data.serverName || null,
      serverIp: data.serverIp || null,
      bannerUrl: data.bannerUrl || null,
      logoUrl: data.logoUrl || null,
      tags: data.tags || undefined,
      creatorId,
      isActive: true,
      visibility: coerceVisibility(data.visibility),
      teaserPublic: data.teaserPublic !== undefined ? Boolean(data.teaserPublic) : true,
    },
  });

  // Rank lock carried onto every draft this template generates
  if (Array.isArray(data.allowedRanks) && data.allowedRanks.length > 0) {
    await prisma.event_template_rank_access.createMany({
      data: normaliseRankSlugs(data.allowedRanks).map((rankSlug) => ({
        templateId: tmpl.templateId,
        rankSlug,
      })),
    });
  }

  // Create default hosts
  if (Array.isArray(data.defaultHosts) && data.defaultHosts.length > 0) {
    await prisma.event_template_hosts.createMany({
      data: data.defaultHosts.map((h) => ({
        templateId: tmpl.templateId,
        userId: h.userId ? parseInt(h.userId) : null,
        discordUserId: h.discordUserId || null,
        displayName: h.displayName || null,
        role: h.role || "host",
      })),
    });
  }

  // Compute first nextGenerateAt
  const nextDate = computeNextGenerationDate(tmpl);
  if (nextDate) {
    await prisma.event_templates.update({
      where: { templateId: tmpl.templateId },
      data: { nextGenerateAt: nextDate },
    });
  }

  return tmpl;
}

/**
 * Update an existing template.
 */
export async function updateTemplate(templateId, data, actorId) {
  const updateData = {};

  if (data.title !== undefined) updateData.title = data.title;
  if (data.description !== undefined) updateData.description = data.description;
  if (data.teaserDescription !== undefined) updateData.teaserDescription = data.teaserDescription;
  if (data.defaultStartTime !== undefined) updateData.defaultStartTime = data.defaultStartTime;
  if (data.defaultEndTime !== undefined) updateData.defaultEndTime = data.defaultEndTime;
  if (data.defaultDurationMins !== undefined) updateData.defaultDurationMins = data.defaultDurationMins;
  if (data.timezone !== undefined) updateData.timezone = data.timezone;
  if (data.recurrenceType !== undefined) updateData.recurrenceType = data.recurrenceType;
  if (data.recurrenceDays !== undefined) updateData.recurrenceDays = data.recurrenceDays;
  if (data.recurrenceEveryDays !== undefined) updateData.recurrenceEveryDays = data.recurrenceEveryDays;
  if (data.draftAdvanceDays !== undefined) updateData.draftAdvanceDays = data.draftAdvanceDays;
  if (data.autoGenerateDrafts !== undefined) updateData.autoGenerateDrafts = data.autoGenerateDrafts;
  if (data.locationLabel !== undefined) updateData.locationLabel = data.locationLabel;
  if (data.locationType !== undefined) updateData.locationType = data.locationType || null;
  if (data.locationDiscordChannelId !== undefined) updateData.locationDiscordChannelId = data.locationDiscordChannelId || null;
  if (data.serverName !== undefined) updateData.serverName = data.serverName;
  if (data.serverIp !== undefined) updateData.serverIp = data.serverIp;
  if (data.bannerUrl !== undefined) updateData.bannerUrl = data.bannerUrl;
  if (data.logoUrl !== undefined) updateData.logoUrl = data.logoUrl;
  if (data.tags !== undefined) updateData.tags = data.tags;
  if (data.isActive !== undefined) updateData.isActive = data.isActive;
  if (data.visibility !== undefined) updateData.visibility = coerceVisibility(data.visibility);
  if (data.teaserPublic !== undefined) updateData.teaserPublic = Boolean(data.teaserPublic);

  const updated = await prisma.event_templates.update({
    where: { templateId: parseInt(templateId) },
    data: updateData,
  });

  if (data.allowedRanks !== undefined) {
    const rankSlugs = normaliseRankSlugs(data.allowedRanks);
    await prisma.event_template_rank_access.deleteMany({
      where: { templateId: parseInt(templateId) },
    });
    if (rankSlugs.length > 0) {
      await prisma.event_template_rank_access.createMany({
        data: rankSlugs.map((rankSlug) => ({ templateId: parseInt(templateId), rankSlug })),
      });
    }
  }

  // Update default hosts
  if (Array.isArray(data.defaultHosts)) {
    await prisma.event_template_hosts.deleteMany({ where: { templateId: parseInt(templateId) } });
    if (data.defaultHosts.length > 0) {
      await prisma.event_template_hosts.createMany({
        data: data.defaultHosts.map((h) => ({
          templateId: parseInt(templateId),
          userId: h.userId ? parseInt(h.userId) : null,
          discordUserId: h.discordUserId || null,
          displayName: h.displayName || null,
          role: h.role || "host",
        })),
      });
    }
  }

  // Recompute nextGenerateAt
  const nextDate = computeNextGenerationDate(updated);
  if (nextDate) {
    await prisma.event_templates.update({
      where: { templateId: parseInt(templateId) },
      data: { nextGenerateAt: nextDate },
    });
  }

  return updated;
}

/**
 * Soft-delete a template.
 */
export async function deleteTemplate(templateId) {
  return prisma.event_templates.update({
    where: { templateId: parseInt(templateId) },
    data: { deletedAt: new Date(), isActive: false },
  });
}

/**
 * Generate a draft event from a template.
 * The event inherits template defaults but remains fully editable.
 */
/**
 * Start and end for a template's default times on `targetDate` (a Date at
 * midnight UTC). Times are stored in UTC ("HH:MM" or "HH:MM:SS"); an end at
 * or before the start runs overnight. Shared by draft generation and the
 * "create event from template" form so both agree.
 */
export function templateTimesOn(template, targetDate) {
  const { defaultStartTime, defaultEndTime, defaultDurationMins } = template;
  const dateStr = targetDate.toISOString().slice(0, 10);

  const startAt = new Date(`${dateStr}T${defaultStartTime || "18:00:00"}Z`);
  if (Number.isNaN(startAt.getTime())) {
    throw new Error(`Template default start time "${defaultStartTime}" is not a valid time.`);
  }

  let endAt;
  if (defaultEndTime) {
    endAt = new Date(`${dateStr}T${defaultEndTime}Z`);
    if (Number.isNaN(endAt.getTime())) {
      throw new Error(`Template default end time "${defaultEndTime}" is not a valid time.`);
    }
    // Handle overnight events
    if (endAt <= startAt) endAt = new Date(endAt.getTime() + 86400000);
  } else if (defaultDurationMins) {
    endAt = new Date(startAt.getTime() + defaultDurationMins * 60000);
  } else {
    endAt = new Date(startAt.getTime() + 3600000); // default 1 hour
  }
  return { startAt, endAt };
}

/**
 * A new-event form pre-filled from a template, in the shape the event editor
 * renders (views/dashboard/events/events-editor.ejs reads `ev`). Dates are
 * filled only when `targetDate` is given -- a master template has none, so
 * the organiser picks the date on the form.
 */
export function eventPrefillFromTemplate(template, targetDate = null) {
  const times = targetDate ? templateTimesOn(template, targetDate) : null;
  return {
    templateId: template.templateId,
    title: template.title,
    description: template.description,
    teaserDescription: template.teaserDescription,
    locationType: template.locationType,
    locationLabel: template.locationLabel,
    locationDiscordChannelId: template.locationDiscordChannelId,
    serverName: template.serverName,
    serverIp: template.serverIp,
    bannerUrl: template.bannerUrl,
    logoUrl: template.logoUrl,
    tags: template.tags,
    visibility: template.visibility || "public",
    teaserPublic: template.teaserPublic !== false,
    rankAccess: (template.rankAccess || []).map((r) => ({ rankSlug: r.rankSlug })),
    hosts: (template.defaultHosts || []).map((h) => ({
      userId: h.userId,
      discordUserId: h.discordUserId,
      displayName: h.displayName,
      role: h.role,
    })),
    announcements: (template.announcements || []).map((a) => ({
      label: a.label,
      announcementType: a.announcementType,
      platform: a.platform,
      channelId: a.channelId,
      contentTemplate: a.contentTemplate,
      body: a.body,
      colourMessageFormat: a.colourMessageFormat,
      link: a.link,
      popupButtonText: a.popupButtonText,
      popupImageUrl: a.popupImageUrl,
      triggerType: a.triggerType,
      offsetMinutes: a.offsetMinutes,
      enabled: a.enabled,
    })),
    ...(times ? { startAt: times.startAt.toISOString(), endAt: times.endAt.toISOString() } : {}),
  };
}

export async function generateDraftFromTemplate(template, targetDate, actorId = null, actorName = "System") {
  const { timezone } = template;
  const { startAt, endAt } = templateTimesOn(template, targetDate);

  const eventData = {
    title: template.title,
    description: template.description,
    teaserDescription: template.teaserDescription,
    eventType: "standard",
    startAt: startAt.toISOString(),
    endAt: endAt.toISOString(),
    timezone,
    locationLabel: template.locationLabel,
    serverName: template.serverName,
    serverIp: template.serverIp,
    bannerUrl: template.bannerUrl,
    logoUrl: template.logoUrl,
    tags: template.tags,
    templateId: template.templateId,
    // A recurring supporter event must generate already-locked drafts; leaving
    // each week's draft public until someone remembers to lock it is exactly
    // the leak this feature exists to prevent.
    visibility: template.visibility || "public",
    teaserPublic: template.teaserPublic !== false,
    allowedRanks: (template.rankAccess || []).map((r) => r.rankSlug),
    hosts: (template.defaultHosts || []).map((h) => ({
      userId: h.userId,
      discordUserId: h.discordUserId,
      displayName: h.displayName,
      role: h.role,
    })),
  };

  const creatorId = actorId || template.creatorId;
  const event = await createEvent(eventData, creatorId, actorName);

  // Copy template announcements to the new event
  if (Array.isArray(template.announcements) && template.announcements.length > 0) {
    await upsertEventAnnouncements(
      event.eventId,
      template.announcements.map((a) => ({
        label: a.label,
        announcementType: a.announcementType,
        platform: a.platform,
        channelId: a.channelId,
        contentTemplate: a.contentTemplate,
        body: a.body,
        colourMessageFormat: a.colourMessageFormat,
        link: a.link,
        popupButtonText: a.popupButtonText,
        popupImageUrl: a.popupImageUrl,
        triggerType: a.triggerType,
        offsetMinutes: a.offsetMinutes,
        enabled: a.enabled,
      })),
      creatorId,
      actorName
    );
  }

  await logEventAudit(
    event.eventId,
    creatorId,
    actorName,
    "template_generated",
    `Draft generated from template #${template.templateId}: "${template.title}"`
  );

  return event;
}

/**
 * Replace all announcements for a template (delete + recreate).
 */
export async function upsertTemplateAnnouncements(templateId, announcements) {
  await prisma.event_template_announcements.deleteMany({
    where: { templateId: parseInt(templateId) },
  });

  if (Array.isArray(announcements) && announcements.length > 0) {
    await prisma.event_template_announcements.createMany({
      data: announcements.map((a) => ({
        templateId: parseInt(templateId),
        label: a.label || null,
        announcementType: a.announcementType || "reminder",
        platform: a.platform || "discord",
        channelId: a.channelId || null,
        contentTemplate: a.contentTemplate || null,
        body: a.body || null,
        colourMessageFormat: a.colourMessageFormat || null,
        link: a.link || null,
        popupButtonText: a.popupButtonText || null,
        popupImageUrl: a.popupImageUrl || null,
        triggerType: a.triggerType || "before_event",
        offsetMinutes: a.offsetMinutes ? parseInt(a.offsetMinutes) : null,
        enabled: a.enabled !== undefined ? a.enabled : true,
      })),
    });
  }
}

/**
 * The site-wide default announcements, without row ids, ready to seed a new
 * event or template. Editing them never touches events or templates that
 * already exist.
 */
export async function getDefaultAnnouncements() {
  const rows = await prisma.event_default_announcements.findMany({ orderBy: { id: "asc" } });
  return rows.map((a) => ({
    label: a.label,
    announcementType: a.announcementType,
    platform: a.platform,
    channelId: a.channelId,
    contentTemplate: a.contentTemplate,
    body: a.body,
    colourMessageFormat: a.colourMessageFormat,
    link: a.link,
    popupButtonText: a.popupButtonText,
    popupImageUrl: a.popupImageUrl,
    triggerType: a.triggerType,
    offsetMinutes: a.offsetMinutes,
    enabled: a.enabled,
  }));
}

/**
 * Replace the site-wide default announcements (delete + recreate).
 */
export async function upsertDefaultAnnouncements(announcements) {
  await prisma.event_default_announcements.deleteMany({});

  if (Array.isArray(announcements) && announcements.length > 0) {
    await prisma.event_default_announcements.createMany({
      data: announcements.map((a) => ({
        label: a.label || null,
        announcementType: a.announcementType || "reminder",
        platform: a.platform || "discord",
        channelId: a.channelId || null,
        contentTemplate: a.contentTemplate || null,
        body: a.body || null,
        colourMessageFormat: a.colourMessageFormat || null,
        link: a.link || null,
        popupButtonText: a.popupButtonText || null,
        popupImageUrl: a.popupImageUrl || null,
        triggerType: a.triggerType || "before_event",
        offsetMinutes: a.offsetMinutes ? parseInt(a.offsetMinutes) : null,
        enabled: a.enabled !== undefined ? a.enabled : true,
      })),
    });
  }
}

/**
 * Compute the next date that a template should generate a draft.
 * Returns a Date or null.
 */
export function computeNextGenerationDate(template, fromDate = null) {
  const base = fromDate ? new Date(fromDate) : new Date();

  if (template.recurrenceType === "once") return null;
  if (!template.autoGenerateDrafts) return null;

  const advanceDays = template.draftAdvanceDays || 7;

  if (template.recurrenceType === "weekly") {
    const days = recurrenceDaysOf(template);
    if (days.length === 0) return null;

    // Find the next occurrence that is at least advanceDays in the future
    const targetEventDate = new Date(base.getTime() + advanceDays * 86400000);
    const targetDay = targetEventDate.getUTCDay();

    // Find soonest day-of-week >= targetDay, then wrap
    for (let offset = 0; offset < 7; offset++) {
      const checkDay = (targetDay + offset) % 7;
      if (days.includes(checkDay)) {
        const result = new Date(targetEventDate);
        const diff = ((checkDay - targetDay) + 7) % 7;
        result.setUTCDate(result.getUTCDate() + diff);
        result.setUTCHours(0, 0, 0, 0);
        // The draft should be generated now (today), the event is on result
        // So generate trigger = result - advanceDays
        const generateOn = new Date(result.getTime() - advanceDays * 86400000);
        // If generateOn is not strictly in the future, advance by one week
        if (generateOn <= base) {
          result.setUTCDate(result.getUTCDate() + 7);
          return new Date(result.getTime() - advanceDays * 86400000);
        }
        return generateOn;
      }
    }
  }

  if (template.recurrenceType === "daily") {
    // Schedule the next generation for the following day at midnight UTC
    const next = new Date(base);
    next.setUTCDate(next.getUTCDate() + 1);
    next.setUTCHours(0, 0, 0, 0);
    return next;
  }

  if (template.recurrenceType === "custom" && template.recurrenceEveryDays) {
    const every = template.recurrenceEveryDays;
    // Anchor the next generation to the current generation time
    const next = new Date(base.getTime() + every * 86400000);
    return next;
  }

  return null;
}

/**
 * The weekday numbers (0 = Sunday) a weekly template runs on. The column is
 * JSON and older rows hold it as a JSON string ("[1,3]") rather than an
 * array; both mean the same thing. Treating the string as "no days" is what
 * made Generate Draft fail with "Could not determine next event date".
 */
export function recurrenceDaysOf(template) {
  let days = template?.recurrenceDays;
  if (typeof days === "string") {
    try {
      days = JSON.parse(days);
    } catch {
      days = days.split(",");
    }
  }
  if (!Array.isArray(days)) return [];
  return [...new Set(days.map(Number).filter((d) => Number.isInteger(d) && d >= 0 && d <= 6))].sort((a, b) => a - b);
}

/**
 * Find the next event occurrence date for a template.
 */
export function computeNextEventDate(template, fromDate = null) {
  const base = fromDate ? new Date(fromDate) : new Date();
  base.setUTCHours(0, 0, 0, 0);

  if (template.recurrenceType === "once") return null;

  if (template.recurrenceType === "weekly") {
    const days = recurrenceDaysOf(template);
    if (days.length === 0) return null;

    const currentDay = base.getUTCDay();
    for (let offset = 1; offset <= 7; offset++) {
      const checkDay = (currentDay + offset) % 7;
      if (days.includes(checkDay)) {
        const next = new Date(base);
        next.setUTCDate(next.getUTCDate() + offset);
        return next;
      }
    }
  }

  if (template.recurrenceType === "daily") {
    const next = new Date(base);
    next.setUTCDate(next.getUTCDate() + 1);
    return next;
  }

  if (template.recurrenceType === "custom" && template.recurrenceEveryDays) {
    const last = template.lastGeneratedAt ? new Date(template.lastGeneratedAt) : base;
    const next = new Date(last.getTime() + template.recurrenceEveryDays * 86400000);
    return next;
  }

  return null;
}

/**
 * Get all templates due for draft generation.
 */
export async function getTemplatesDueForGeneration() {
  const now = new Date();
  return prisma.event_templates.findMany({
    where: {
      isActive: true,
      deletedAt: null,
      autoGenerateDrafts: true,
      nextGenerateAt: { lte: now },
    },
    include: { defaultHosts: true, rankAccess: true, announcements: { orderBy: { id: "asc" } } },
  });
}

/**
 * Soft-delete template-generated events that are still in draft/pending_review
 * and whose startAt has already passed. These are "unused" events that were
 * auto-created but never promoted before their scheduled time.
 *
 * Returns the count of deleted events.
 */
export async function cleanupStaleTemplateEvents() {
  const now = new Date();

  const stale = await prisma.events.findMany({
    where: {
      templateId: { not: null },
      status: { in: ["draft", "pending_review"] },
      startAt: { lt: now },
      deletedAt: null,
    },
    select: { eventId: true, title: true, templateId: true },
  });

  if (stale.length === 0) return 0;

  await prisma.events.updateMany({
    where: { eventId: { in: stale.map((e) => e.eventId) } },
    data: { deletedAt: now },
  });

  return stale.length;
}

/**
 * Mark a template as having just generated a draft and set the next generation time.
 */
export async function markTemplateGenerated(templateId, generatedAt = new Date()) {
  const tmpl = await prisma.event_templates.findUnique({
    where: { templateId: parseInt(templateId) },
  });

  if (!tmpl) return;

  const nextGenerate = computeNextGenerationDate(tmpl, generatedAt);

  return prisma.event_templates.update({
    where: { templateId: parseInt(templateId) },
    data: {
      lastGeneratedAt: generatedAt,
      nextGenerateAt: nextGenerate || null,
    },
  });
}
